### ISSUE TITLE
How do you integrate your tilemap into your game?

### ISSUE THREAD

**Issue by gamemake-eng** [victorqribeiro/tileEditor#2]
I've been wanting to add a tilemap into a game but I never knew how to. I saw your videos but you never showed any code or open sourced it. Is there any way to integrate tilemaps made in your editor into a JavaScript game.

**Comment by victorqribeiro** [comment]
when you save a map from tile editor you have N two dimensional arrays with coordinates on how to draw each tile of a tile set. for instance, you can draw the map on your game with the following three loops:

```javascript
    for (let l = 0; l < map.nLayers; l++) {
        for (let i = 0; i < map.intH; i++) {
            for (let j = 0; j < map.intW; j++) {
                const coords = map.layers[l][i][j]
                if(!coords)
                    continue
                c.drawImage(
		  mapTexture, 
		  coords[1] * 16, 
		  coords[0] * 16, 
		  16, 
		  16,
		  j * 64, 
		  i * 64, 
		  64,
		  64
	       )
            }
        }
    }
```

In the example above I'm drawing a tile set that was originally 16 x 16 pixels with the final size of 64 x 64 pixels

**Comment by gamemake-eng** [comment]
Thank you very much!!! Sorry for late reply
